---
output:
  pdf_document:
    toc: no
    dev: cairo_pdf
    latex_engine: xelatex
  html_document:
    toc: no
    toc_float: yes
    toc_collapsed: no
    highlight: kate
    theme: spacelab
    fig_caption: yes
    df_print: paged
classoption: landscape, a4paper
geometry: margin=1in
params:
  ADSL_DSIN: adsl
  A_DSIN: adae
  ADSL_SUBSET: "SAFFL == 'Y'"
  POPULATION_FILTER: SAFFL
  OVERALL_SUBSET: !is.na(ASTDT)
  AE_FILTER: TREATMENT EMERGENT
  A_SUBSET: !r NA
  AEOBSRESIDUAL: !r NA_real_
  TRTVAR: TRTA
  TRTSORT: TRTAN
  TRTBIGN: Y
  TRTTOT: N
  TRTMISSYN: N
  GRPVARMISS: Y
  SUBGRPVAR: !r NA_character_
  SUBBIGN: N
  SUBGRPTOT: N
  SUMMARY_BY: Patients
  HT: AEBODSYS
  LT: AEDECOD
  CUTOFF_WHERE: "PCT >= 5"
  APPLY_HROW_CUTOFF: Y
  NO_LWTIER_DISPYN: N
  SUM_ROWYN: N
  SUM_ROW_LABEL: Participants with Any Adverse Event
  PCTSYN: Y
  DECIMAL: 1
  SORTOPT: Ascending
  SORTVAR: Count
  DPT_HEAD_LABEL: Number of Participants Evaluable for AEs_Number (%) of Participants by System Organ Class and Preferred Term
  TITLE: Participants in Any Treatment Group by MedDRA SOC/PT
  FOOTNOTE: "n is the number of Participants \\\\ Classifications of adverse events are based on the
  Medical Dictionary for Regulatory Activities. (MedDRA v21.1) \\\\ Dashed Vertical line represents risk value reference line \\\\ The number of participants reporting at least 1 occurrence of the event specified."
header-includes:
  - \usepackage{fancyhdr}
  - \usepackage{lastpage}
  - \pagestyle{fancy}
  - \fancyhf{}
  - \renewcommand{\headrulewidth}{0pt}
  - '`r paste0("\\fancyhead[L]{\\textbf{", params$TITLE, "}}")`'
  - '`r paste0("\\fancyfoot[L]{", params$FOOTNOTE, "}")`'
  - \setlength{\headsep}{10pt}
  - \setlength{\headheight}{30pt}
  - \fancyhead[R]{Page \thepage\, of\, \pageref*{LastPage}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, ft.keepnext = FALSE, message = FALSE, warning = FALSE)
## load libraries
library(carver)
library(dplyr, include.only = c("if_else"))
library(stringr, include.only = c("str_glue", "str_replace_all", "str_which"))
library(rlang, include.only = c("parse_expr"))
library(flextable, include.only = c("width", "autofit", "height"))
is_html <- knitr::opts_knit$get("rmarkdown.pandoc.to") == "html"
```

```{r adae_mentry}
adsl <- eval(parse_expr(params$ADSL_DSIN))
adae <- eval(parse_expr(params$A_DSIN))
### Pre-process AE
adae_prep <- adae |>
  ae_pre_processor(
    fmq_data = NA_character_,
    ae_filter = params$AE_FILTER,
    subset = params$A_SUBSET,
    obs_residual = params$AEOBSRESIDUAL
    )
### Merge with adsl
dsin_merged <- dataset_merge(
  adsl,
  adae_prep$data,
  byvars = intersect(names(adsl), names(adae_prep$data)),
  subset = list(params$ADSL_SUBSET, NA_character_)
)

```

```{r process}
dsin_mentry <-
  mentry(
    datain = dsin_merged,
    subset = params$OVERALL_SUBSET,
    byvar = params$HT,
    trtvar = params$TRTVAR,
    trtsort = params$TRTSORT,
    subgrpvar = params$SUBGRPVAR,
    trttotalyn = params$TRTTOT,
    add_grpmiss = params$GRPVARMISS,
    sgtotalyn = params$SUBGRPTOT,
    pop_fil = params$POPULATION_FILTER,
    trtmissyn = params$TRTMISSYN
  )

## combine `ae_filter` and `a_subset` into a single analysis subset condition
rpt_data <- dsin_mentry |>
  occ_tier_summary(
    a_subset = adae_prep$a_subset,
    cutoff_where = params$CUTOFF_WHERE,
    hterm = params$HT,
    lterm = params$LT,
    apply_hrow_cutoff = params$APPLY_HROW_CUTOFF,
    sort_opt = params$SORTOPT,
    sort_var = params$SORTVAR,
    nolwrtierdispyn = params$NO_LWTIER_DISPYN,
    pctsyn = params$PCTSYN,
    sigdec_cat = params$DECIMAL,
    sum_row = params$SUM_ROWYN,
    sum_row_label = params$SUM_ROW_LABEL
  )
```

```{r tier_summary,  results='asis', ft.align="left"}
# Title
if (is_html) {
  cat("###", gsub(" \\\\ ", "  \n", params$TITLE, fixed = TRUE), "  \n")
}
# Check for zero rows, print otherwise as table output
if (nrow(rpt_data) == 0) {
  output <- empty_tbl()
} else {
  # Add N count to col header
  output <- rpt_data |>
  display_bign_head(
    mentry_data = dsin_mentry,
    trtbignyn = params$TRTBIGN,
    subbignyn = params$SUBBIGN
  ) |>
  tbl_processor() |>
  tbl_display(
    dpthead = params$DPT_HEAD_LABEL,
    boldheadyn = "Y"
  ) |>
  flextable::autofit() |>
  {\(x) width(x, width = dim(x)$widths * 7 / sum(dim(x)$widths))}() # nolint
}
output
if (is_html) {
  cat(gsub(" \\\\ ", "  \n", params$FOOTNOTE, fixed = TRUE))
}
```

