---
output:
  pdf_document:
  html_document:
    df_print: paged
classoption: landscape, a4paper
params:
  A_DSIN: adae
  OVERALL_SUBSET: "!is.na(ASTDT)"
  AE_FILTER: TREATMENT EMERGENT
  A_SUBSET: "AOCCPFL == 'Y'"
  AEOBSRESIDUAL: !r NA_real_
  TRTVAR: TRTA
  TRTSORT: TRTAN
  FMQ_DATA: FMQ_Consolidated_List
  SUMMARY_BY: Events
  HT_VAR: "FMQ_NAM"
  HT_VAL: "ABDOMINAL PAIN"
  HT_SCOPE: "Narrow"
  LT_VAR: "AEDECOD"
  LT_VAL: "ABDOMINAL DISCOMFORT"
  LT_SCOPE: "Narrow"
  REFVAL: 2
  TITLE: "Adverse Event Analysis of FMQ and PT"
  FOOTNOTE: ""
  INTERACTIVE: N
header-includes:
  - \usepackage{fancyhdr}
  - \usepackage{lastpage}
  - \pagestyle{fancy}
  - \fancyhf{}
  - \fancyhead[R]{Page \thepage\, of\, \pageref*{LastPage}}
  - \renewcommand{\headrulewidth}{0pt}
  - '`r paste0("\\fancyhead[L]{\\textbf{", params$TITLE, "}}")`'
  - '`r paste0("\\fancyfoot[L]{", params$FOOTNOTE, "}")`'
  - \setlength{\headsep}{10pt}
  - \setlength{\headheight}{50pt}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE, warning = FALSE, message = FALSE, fig.width = 10,
  fig.height = 5, fig.align = "center"
)
## load libraries
library(carver)
library(rlang, include.only = "parse_expr")
```


```{r adae_prep}

## Prepare AE data
adae_prep <- eval(parse_expr(params$A_DSIN)) |>
  ### Pre-process AE
  ae_pre_processor(
    fmq_data = eval(parse_expr(params$FMQ_DATA)),
    ae_filter = params$AE_FILTER,
    subset = params$A_SUBSET,
    obs_residual = params$AEOBSRESIDUAL
  )
adae_entry <- mentry(
  adae_prep$data,
  subset = params$OVERALL_SUBSET,
  trtvar = params$TRTVAR,
  trtsort = params$TRTSORT,
  trttotalyn = "N",
  byvar = params$HT_VAR
)

prep_event_analysis <- adae_entry |>
  process_event_analysis(
    a_subset = adae_prep$a_subset,
    summary_by = params$SUMMARY_BY,
    hterm = params$HT_VAR,
    ht_val = params$HT_VAL,
    ht_scope = params$HT_SCOPE,
    lterm = params$LT_VAR,
    lt_val = params$LT_VAL,
    lt_scope = params$LT_SCOPE
  )

plot_output <- event_analysis_plot(
  datain = prep_event_analysis,
  fig.align = "h",
  disp.proportion = "4~6",
  ref_line = params$REFVAL,
  x_tickangle = 15,
  pt_color = "royalblue3",
  interactive = params$INTERACTIVE
)
```


```{r, include=TRUE, echo=FALSE, results="asis"}
plot_output
```

```{css styling}
h4 {
    font-size: 14px;
    font-weight: bold;
    color: #666666 !important;
}
```
