# Copyright 2024 Pfizer Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#' Generate Volcano Plot of Adverse Events from Risk values of treatment pairs
#'
#' @param datain (`data.frame`)\cr Input dataset containing statistics for treatment
#' pairs from AE data, generated by `risk_stat()`.
#' @param axis_opts A `list` of axis specific options retrieved from `plot_axis_opts()` and
#' `ae_volcano_opts()`.
#' @param legend_opts Legend styling option, a `list` containing `label`, `pos`(position) and
#' `dir` (direction).
#' @param xref (`numeric`)\cr Numeric vector, from `ae_volcano_opts` First value will be the main
#' reference, all drawn vertically.
#' @param pvalue_sig (`numeric`)\cr p-value cut-off, filter values with adjusted `p` less than
#' this argument
#' @param interactive Return interactive plot or static. Values: "Y"/"N".
#'
#' @details
#' It is recommended not to change `pos` and `dir` in `legend_opts`; additionally, these options
#' are fixed for the case of `interactive` = Y and cannot be changed.
#' `xref` must be of length 2 or more.
#' Input `datain` from `risk_stat()` should only contain one treatment pair and not more.
#'
#' @return a ggplot object (volcano plot)
#' @export
#'
#' @examples
#' data("adae")
#'
#' ae_pre <- ae_pre_processor(
#'   datain = adae,
#'   obs_residual = 0,
#'   fmq_data = NA
#' )
#'
#' ae_entry <- mentry(
#'   datain = ae_pre$data,
#'   subset = NA,
#'   byvar = "AEBODSYS",
#'   trtvar = "TRTA",
#'   trtsort = "TRTAN",
#'   subgrpvar = NA,
#'   trttotalyn = "N",
#'   add_grpmiss = "N",
#'   sgtotalyn = "N",
#'   pop_fil = "SAFFL"
#' )
#'
#' ae_risk <- risk_stat(
#'   datain = ae_entry,
#'   a_subset = ae_pre$a_subset,
#'   summary_by = "Patients",
#'   eventvar = "AEDECOD",
#'   ctrlgrp = "Placebo",
#'   trtgrp = "Xanomeline High Dose",
#'   statistics = "Risk Ratio",
#'   alpha = 0.05,
#'   cutoff_where = "FREQ >5",
#'   sort_opt = "Ascending",
#'   sort_var = "Count"
#' )
#'
#' vaxis_opts <- ae_volcano_opts(
#'   ae_risk,
#'   "Control",
#'   "Exposure",
#'   pvalue_trans = "-log10"
#' )
#'
#' axis_opts <- plot_axis_opts(
#'   ylinearopts = vaxis_opts$ylinearopts,
#'   yaxis_scale = vaxis_opts$yaxis_scale,
#'   xaxis_label = vaxis_opts$xaxis_label,
#'   yaxis_label = vaxis_opts$yaxis_label
#' )
#'
#' ae_risk |>
#'   ae_volcano_plot(
#'     axis_opts = axis_opts,
#'     xref = vaxis_opts$xref
#'   )
#'
ae_volcano_plot <- function(datain,
                            axis_opts,
                            legend_opts = list(
                              label = "",
                              pos = "bottom",
                              dir = "horizontal"
                            ),
                            xref = c(1, 0, 2),
                            pvalue_sig = 0.05,
                            interactive = "N") {
  ### Construction of volcano plot
  datain <- datain |>
    filter(!.data[["RISK"]] %in% c(NA, Inf)) |>
    mutate(key = dplyr::row_number())
  # Check if getstats data is empty:
  stopifnot("Risk data is empty" = nrow(datain) != 0)
  stopifnot(
    "Only one treatment pair should be passed to volcano plot" =
      length(unique(datain[["TRTPAIR"]])) == 1
  )
  gplot <-
    ggplot(
      datain,
      aes(
        x = .data[["RISK"]],
        y = .data[["PVALUE"]],
        text = .data[["HOVER_TEXT"]],
        fill = .data[["BYVAR1"]],
        key = .data[["key"]]
      )
    ) + # color code by SOC
    geom_point(aes(size = .data[["CTRL_N"]]), pch = 21, alpha = 0.5)

  # Error when there are no adjusted p-values <= 0.05 so remove FDR adjusted P when no
  # adjusted p <= p value cutoff
  check_sig <- datain |>
    filter(.data[["ADJPVALUE"]] <= pvalue_sig) |>
    arrange(desc(.data[["ADJPVALUE"]]))
  # Reference for p value cutoff
  if (nrow(check_sig) != 0) {
    pvalue_adj <- check_sig$PVALUE[1]
    gplot <- gplot +
      geom_hline(
        yintercept = pvalue_adj,
        color = "grey30",
        linetype = "dotted"
      )
  }
  gplot <- gplot +
    geom_hline(
      yintercept = pvalue_sig,
      color = "grey30",
      linetype = "dashed"
    ) +
    geom_vline(
      xintercept = xref[1],
      color = "grey30",
      linetype = "dashed"
    ) +
    geom_vline(
      xintercept = xref[-1],
      color = "grey30",
      linetype = "dotted"
    ) +
    scale_size_continuous(range = c(1, 8), guide = "none") +
    scale_fill_discrete(name = legend_opts$label) +
    scale_y_continuous( # p-value transformation
      name = axis_opts$yaxis_label,
      trans = axis_opts$yaxis_scale,
      breaks = axis_opts$Ybrks,
      labels = axis_opts$Yticks,
      expand = expansion(mult = c(0.05, 0.05))
    ) +
    scale_x_continuous(
      name = axis_opts$xaxis_label,
      breaks = axis_opts$Xbrks,
      limits = axis_opts$Xlims,
      expand = expansion(mult = c(0.05, 0.05))
    ) +
    theme_std(axis_opts = axis_opts, legend_opts = legend_opts) +
    theme(
      legend.text = element_text(size = 4),
      legend.title = element_text(size = 5)
    )
  # Interactive plot;
  if (interactive == "Y") {
    gplot <- gplot |>
      as_plotly(
        legend_opts = list(label = legend_opts$label, pos = c(0.5, -0.2), dir = "h"),
        height = 700,
        width = 800,
        axis_opts = list(
          xopts = list(
            showticklabels = TRUE,
            showline = TRUE
          ),
          yopts = list(
            showticklabels = TRUE,
            showline = TRUE
          )
        )
      )
  }
  return(gplot)
}

#' Volcano Plot axis Options
#'
#' @param datain Input data for volcano plot
#' @param trt1_label Control Treatment label
#' @param trt2_label Other treatment label
#' @param statistic Statistic used for risk analysis
#' @param pvalue_trans Required pvalue transformation. Values: "none"/"-log10"
#' @param xref_offset Offset value for X axis reference line; offset from 0 is `statistic` is Risk
#' Difference and from 1 if `statistic` is Risk Ratio.
#'
#' @return List of volcano-specific options
#' @export
#'
#' @examples
#' data("adae")
#'
#' ae_pre <- ae_pre_processor(
#'   datain = adae,
#'   obs_residual = 0,
#'   fmq_data = NA
#' )
#'
#' ae_entry <- mentry(
#'   datain = ae_pre$data,
#'   subset = NA,
#'   byvar = "AEBODSYS",
#'   trtvar = "TRTA",
#'   trtsort = "TRTAN",
#'   subgrpvar = NA,
#'   trttotalyn = "N",
#'   add_grpmiss = "N",
#'   sgtotalyn = "N",
#'   pop_fil = "SAFFL"
#' )
#'
#' ae_risk <- risk_stat(
#'   datain = ae_entry,
#'   a_subset = ae_pre$a_subset,
#'   summary_by = "Patients",
#'   eventvar = "AEDECOD",
#'   ctrlgrp = "Placebo",
#'   trtgrp = "Xanomeline High Dose",
#'   statistics = "Risk Ratio",
#'   alpha = 0.05,
#'   cutoff_where = "FREQ >5",
#'   sort_opt = "Ascending",
#'   sort_var = "Count"
#' )
#' ae_volcano_opts(ae_risk,
#'   pvalue_trans = "-log10"
#' )
ae_volcano_opts <- function(datain,
                            trt1_label = "Control",
                            trt2_label = "Exposure",
                            statistic = "Risk Ratio",
                            pvalue_trans = "none",
                            xref_offset = 1) {
  datain <- datain |> na.omit()
  N2 <- unique(datain$TOTAL_N[datain$CTRL_N != datain$FREQ])
  N1 <- unique(datain$TOTAL_N[datain$TOTAL_N != N2])
  xlab <- glue::glue(
    "
<--- Favors {trt1_label} (N={N1}) ---- \\
Favors {trt2_label} (N={N2}) --->\n{statistic}"
  )
  if (pvalue_trans == "-log10") {
    ylab <- "-log10 p-value"
    ylinearopts <- list(breaks = as.numeric(paste0("1e-", 0:20)), labels = as.character(0:20))
    ytrans <- reverselog_trans(10)
  } else {
    ylab <- "p-value"
    ylinearopts <- list(
      breaks = c(0.05, 0, rep(1, 10) / 10^(9:0)),
      labels = as.character(c(0.05, 0, rep(1, 10) / 10^(9:0)))
    )
    ytrans <- "identity"
  }
  refval <- ifelse(grepl("Ratio", statistic), 1, 0)
  xref <- c(refval, refval - xref_offset, refval + xref_offset)
  return(list(
    xaxis_label = xlab, yaxis_label = ylab,
    ylinearopts = ylinearopts, yaxis_scale = ytrans, xref = xref
  ))
}
