# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  pull_request:
    branches: [main, devel, devtools_check]

name: lint-changed-files

jobs:
  lint-changed-files:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::gh
            r-lib/lintr
            any::purrr
          needs: check

      - name: Install package
        run: R CMD INSTALL .

      - name: Extract and lint files changed by this PR
        run: |
          options(crayon.enabled = TRUE)
          library(lintr)
          files <- gh::gh("GET https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files")
          changed_files <- purrr::map_chr(files, "filename")
          all_files <- list.files(recursive = TRUE)
          exclusions_list <- as.list(setdiff(all_files, changed_files))
          lint_package(linters = linters_with_defaults(
            line_length_linter(100),
            object_length_linter(50L),
            cyclocomp_linter(100L),
            indentation_linter = NULL,
            object_usage_linter = NULL, 
            object_name_linter = NULL
          ), exclusions = exclusions_list)
        shell: Rscript {0}