# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, devel]
  pull_request:
    branches: [devel, main, devtools_check]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::covr
            local::.

      - name: Test package coverage
        run: |
          options(crayon.enabled = TRUE)
          library(covr)
          coverage <- covr::package_coverage(
            quiet = FALSE,
            line_exclusions = list("R/app_server.R", "R/app_ui.R", "R/app_config.R", "R/run_app.R")
            )
          print(coverage)
          percent_coverage <- covr::percent_coverage(coverage)
          threshold <- 10
          cli::cli_rule()
          if (percent_coverage < threshold) {
            cli::cli_abort("Code coverage is below the required threshold ({threshold}%).")
          } else {
            cli::cli_alert_success("Code coverage is above the required threshold ({threshold}%).")
          }
          cli::cli_rule()
        shell: Rscript {0}